name: build
on:
    push:
        branches: [dev]
jobs:
    Build-Deploy:
        name: Build-Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: uses: actions/checkout@v3
              with:
                  node-version: '16'

            - name: 🔨 Build
              run: |
                  yarn
                  yarn build
            - name: 🎉 Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: main
                folder: build
